### ISSUE TITLE
On parametric test, add a way to specify a commit SHA for building the tracer

### ISSUE THREAD

**Issue by cbeauchesne** [DataDog/system-tests#1094]

**Comment by ahmed-mez** [comment]
That'd be super useful for the Go tracer!
Currently we manually update the app in apps/golang to use a specific commit SHA, see how it's done in our CI https://github.com/DataDog/dd-trace-go/blob/v1.49.1/.github/workflows/parametric-tests.yml#L38-L42 - and we have to do the same when we run the tests locally.

**Comment by cbeauchesne** [comment]
closing this, as it's using the usual `install_ddtrace` scripts of regular end-to-end scenarios.
