### ISSUE TITLE
Containers are intermittently failing to start for parametric tests

### ISSUE THREAD

**Issue by rochdev** [DataDog/system-tests#2734]
It looks like parametric tests have been particularly flaky since this week. They were already flaky before but at this point most CI runs are failing. It looks like containers fail to start because the port cannot be allocated. I'm not sure where to look and I don't know the port allocation logic, but I figured I would at least open an issue so that the problem is known.

**Comment by cbeauchesne** [comment]
Well, here is a very good suspect : https://github.com/DataDog/system-tests/blob/5bbe189e07f2f8def444e7bef7fff5d37d784e70/tests/parametric/conftest.py#L74, race condition, with 16 runners, it's very probable to have issues

**Comment by rochdev** [comment]
I don't know Python, but if this requests the port directly from the kernel, it should be impossible for a race condition to occur.

**Comment by cbeauchesne** [comment]
it open the socket, get the port, close the socket. At this point, the port is free to be reused, no ?

**Comment by rochdev** [comment]
Yes that's my point, instead of trying to figure out a port to use, it should just open the socket, get its port, and use that same socket. We had the same issue in dd-trace-js for a long time with our use of `get-port`, and we never figured out a proper way to fix it without a ton of complexity, so we ended up just refactoring everything to just use the socket that was opened in the first place.

**Comment by rochdev** [comment]
It's also worth noting that we were having the issue with a single thread, so doing this is definitely prone to weird errors regardless of concurrency.

**Comment by rochdev** [comment]
It looks like the port eventually makes it to the `docker_run` function that then passes it to Docker. Could the code instead always pass `0` to Docker to let it get a socket on a random port and then grab the port from Docker directly instead?

**Comment by cbeauchesne** [comment]
> It looks like the port eventually makes it to the docker_run function that then passes it to Docker. Could the code instead always pass 0 to Docker to let it get a socket on a random port and then grab the port from Docker directly instead?

Trying that right now.

**Comment by cbeauchesne** [comment]
Feedback after few days of tears and blood

1. let docker allocate the host port
   * works like a dream locally on macOS
   * fails miserably on github action, randomly sending payloads to the wrong agent container. No idea why
2. trying to use some filelock trick, and keep the hack `socket.open`
  * fails miserably
3. I went threw the mindstate where I disable xdist.
4. back to the bench, currently trying to use predetermined ports
