### ISSUE TITLE
Remove the local ASM config in remote config scenarios with `ASM_FEATURES`

### ISSUE THREAD

**Issue by simon-id** [DataDog/system-tests#559]
According to the spec, the remote config AppSec 1 click activation feature should not be active when appsec has been locally configured. We need to remove any DD_APPSEC_ENABLED for those test to work as intended.

**Comment by ameske** [comment]
Address in https://github.com/DataDog/system-tests/pull/565 by b562c9c351a9b46f4dade04c5ed9dabd6bc14c17
