### ISSUE TITLE
Do not start cassandra and mongodb when unnecessary 

### ISSUE THREAD

**Issue by simon-id** [DataDog/system-tests#587]
Starting cassandra and mongodb etc... is cumbersome when you know for sure your library or your tests do not care about it.
Loic suggested to put those tests in a different scenario.

**Comment by cbeauchesne** [comment]
As only a small test use it, I agree to remove it from the default scenario.

The plan is 

* make an TRACER_INTEGRATIONS scenario
* only start cassandra and mongo on this scenario
