### ISSUE TITLE
parametric/apps/golang: Flush() doesn't flush stats

### ISSUE THREAD

**Issue by katiehockman** [DataDog/system-tests#596]
The `FlushTraceStats` function for the Go implementation should be able to call `Flush()`, but this function doesn't actually flush the trace stats. This causes problems for the some of the tests which are then forced to call `Stop()`.

https://github.com/DataDog/system-tests/pull/576 will include some stopgaps, but we need to investigate if the Go Tracer should actually be flushing stats in `Flush()`

/cc @Kyle-Verhoog

**Comment by cbeauchesne** [comment]
@katiehockman can we close this issue ?

**Comment by katiehockman** [comment]
Nope it's still a bug, albeit it could be argued that the bug is actually in the Go tracer, so I can file one there and link to this issue. Right now there is a temporary work (calling close when it should call flush for Go tests) around in the parametric tests that we need to remove once this is resolved, so it would be good to track this here to make sure we don't forget to remove it..
