### ISSUE TITLE
Execute test scenarios in parallel in CI

### ISSUE THREAD

**Issue by simon-id** [DataDog/system-tests#598]
The CI taking 30 minutes to complete does not spark joy. I've seen that the scenarios are executed 1 by 1 where they could be parallelized. In a local dev env it wouldn't make sense but in CI I'm guessing it does.

**Comment by cbeauchesne** [comment]
Ci workflow : 

Batch 1, all in parrallel
* Build runner, proxies, agent
* build for dev and prod all weblog images

Batch 2: 
* run all scenario on all weblog images

**Comment by cbeauchesne** [comment]
Well. We have 26 scenarios, 56 variants, two set of run (dev and prod).

It gives 2912 jobs to run in parallel, on 2912 machines .... 

Turns out we do not have this number of machine ... 

I'll try to find a compromise ...

**Comment by cbeauchesne** [comment]
Well, not perfect, because of limitations of github actions (what, you cant run 3k job in parallel ? :D). The overall time should divided by two.
