### ISSUE TITLE
Make system tests works on forks ?

### ISSUE THREAD

**Issue by cbeauchesne** [DataDog/system-tests#975]

**Comment by cbeauchesne** [comment]
idea 1 : distant repo has a valid DD_API_KEY in secrets
idea 2: system test repos hosts the process

**Comment by rochdev** [comment]
Some context of why this would be useful:

System tests always fail on forks. This means that we can never know if an external PR breaks something until it's merged. It also means that we cannot require system tests to pass in order to merge, otherwise it blocks merging forks completely.

**Comment by cbeauchesne** [comment]
idea 3 : mocked backend

it will work for almost all scenario, as we don't test responses from backend. And will be able to use a fake key.

**Comment by cbeauchesne** [comment]
idea 4 that actually work fine : using a fake DD_API_KEY. Turns out this key does not have to be a real one to have everything working \o/
